name: Check Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Poetry Setup
        uses: snok/install-poetry@v1

      - name: Debug
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of repository root:"
          ls -F
          echo "Contents of Fewpy subdirectory:"
          ls -F Fewpy/
          if [ -f "pyproject.toml" ]; then
            echo "pyproject.toml found in repo root."
          elif [ -f "Fewpy/pyproject.toml" ]; then
            echo "pyproject.toml found in Fewpy/ subdirectory."
          else
            echo "pyproject.toml NOT found in common locations."
          fi

      - name: Install uv based on the version defined in pyproject.toml
        uses: astral-sh/setup-uv@v6
        with:
          version-file: "pyproject.toml"

      - name: Install uv based on the version defined in pyproject.toml
        uses: astral-sh/setup-uv@v6
        with:
          version-file: "pyproject.toml"
          working-directory: "../"

      - name: Run Lint Check
        id: lint
        run: |
          set -o pipefail
          uv run ruff format --check .
          uv run ruff check .
        continue-on-error: true

      - name: Lint Failed
        if: steps.lint.outcome != 'success'
        run: |
          echo -e "\033[0;31m Linting failed. See the errors below:\n"
          cat lint_output.log
          exit 1
